name: MLOps Class Task
on: 
  pull_request_target:
    types: [ closed ]
    branches: [ main ] 
jobs:
  if_merged:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.16
    - name: Install dependencies
      run: |
        make install
    - name: Format
      run: |
        make format
